# Generated by Django 5.0.7 on 2024-07-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Введите действие.', max_length=255, verbose_name='Действие')),
                ('time', models.TimeField(help_text='Введите время.', verbose_name='Время')),
                ('place', models.CharField(help_text='Введите место.', max_length=255, verbose_name='Место')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Приятная привычка?', verbose_name='Приятная привычка')),
                ('period', models.PositiveIntegerField(default=1, help_text='Введите периодичность.', verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, help_text='Введите вознаграждение.', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.PositiveIntegerField(help_text='Введите время в секундах.', verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, help_text='Публичная привычка?', verbose_name='Публичная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
